version: "3"

services:
  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672

  worker:
    image: worker
    container_name: worker
    build:
      context: "./backend"
      dockerfile: "docker/worker.Dockerfile"
    volumes:
      - ./backend:/home/backend
    links:
      - rabbitmq
    env_file:
      - backend/.env
    depends_on:
      - rabbitmq
      - db

  backend:
    image: backend
    container_name: backend
    build:
      context: "./backend"
      dockerfile: "docker/backend.Dockerfile"
    volumes:
      - ./backend:/home/backend
    ports:
      - 5000:5000
    env_file:
      - backend/.env
      - backend/.flaskenv
    depends_on:
      - db
      - rabbitmq
      - worker

  frontend:
    image: frontend
    build:
      context: "./frontend"
      dockerfile: "frontend.Dockerfile"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
