version: '3'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306:3306
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password

  webapp:
    image: webapp
    build:
      context: '.'
      dockerfile: 'webapp.Dockerfile'
    volumes:
      - ${PWD}/webapp:/home/webapp
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
