version: "3"

services:
  db:
    image: mysql
    container_name: db
    env_file:
      - backend/.env.dev
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    env_file:
      - backend/.env.dev
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  worker:
    image: backend
    container_name: worker
    environment:
      - SERVICE=worker
    env_file:
      - backend/.env
      - backend/.env.dev
    volumes:
      - ./backend:/home/backend
    depends_on:
      - backend
      - redis
      - rabbitmq

  scheduler:
    image: backend
    container_name: scheduler
    environment:
      - SERVICE=scheduler
    env_file:
      - backend/.env
      - backend/.env.dev
    volumes:
      - ./backend:/home/backend
    depends_on:
      - backend
      - redis
      - rabbitmq

  api:
    image: backend
    container_name: api
    environment:
      - SERVICE=api
    env_file:
      - backend/.env
      - backend/.env.dev
      - backend/.flaskenv
    depends_on:
      - db
      - backend
      - worker
      - redis
      - rabbitmq
      - airflow

    ports:
      - 5000:5000
    volumes:
      - ./backend:/home/backend

  backend:
    image: backend
    container_name: backend
    build:
      context: "./backend"
      dockerfile: "docker/backend.Dockerfile"
    env_file:
      - backend/.env
      - backend/.env.dev
      - backend/.flaskenv

  airflow:
    image: airflow
    container_name: airflow
    build:
      context: "./backend"
      dockerfile: "docker/airflow.Dockerfile"
    depends_on:
      - backend
      - db
      - worker
      - rabbitmq
    ports:
      - 8080:8080
      - 8793:9793
      - 5555:5555
    env_file:
      - backend/.env.dev
    volumes:
      - ./backend/airflow:/usr/local/airflow
      - ./backend:/usr/local/backend


  # flower isn't necessary -- it's just a nice service for checking out what's going on with rabbit MQ
  flower:
    container_name: flower
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_HOST}:5672
      - FLOWER_PORT=5555
    ports:
      - 5555:5555

