version: "3"

services:
  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  worker:
    image: backend
    container_name: worker
    environment:
      - SERVICE=worker
    env_file:
      - backend/.env
    volumes:
      - ./backend:/home/backend

  scheduler:
    image: backend
    container_name: scheduler
    environment:
      - SERVICE=scheduler
    env_file:
      - backend/.env
    volumes:
      - ./backend:/home/backend

  api:
    image: backend
    container_name: api
    environment:
      - SERVICE=api
    env_file:
      - backend/.env
      - backend/.flaskenv
    depends_on:
      - db
      - redis
      - rabbitmq
      - worker
    ports:
      - 5000:5000
    volumes:
      - ./backend:/home/backend

  backend:
    image: backend
    container_name: backend
    build:
      context: "./backend"
      dockerfile: "docker/backend.Dockerfile"
    env_file:
      - backend/.env
      - backend/.flaskenv

  # flower isn't necessary -- it's just a nice service for checking out what's going on with rabbit MQ
  flower:
    container_name: flower
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:5672
      - FLOWER_PORT=5555
    ports:
      - 5555:5555

