version: "3"

services:
  db:
    image: mysql
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306:3306

  backend:
    image: backend
    build:
      context: "./backend"
      dockerfile: "backend.Dockerfile"
    volumes:
      - ./backend:/home/backend
    ports:
      - 5000:5000
    env_file:
      - backend/.env
      - backend/.flaskenv
    depends_on:
      - db

  frontend:
    image: frontend
    build:
      context: "./frontend"
      dockerfile: "frontend.Dockerfile"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
