version: "3"

services:
  db:
    image: mysql
    container_name: db
    env_file:
      - backend/.env.dev
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: --init-file /init.sql
    volumes:
      - ./backend/docker/init.sql:/init.sql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    env_file:
      - ./backend/.env.dev
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  airflow:
    image: backend
    container_name: airflow
    environment:
      - SERVICE=airflow
    env_file:
      - ./backend/.env
      - ./backend/.env.dev
    depends_on:
      - backend
      - db
      - airflow-worker
      - rabbitmq
      - redis
    ports:
      - 8080:8080
      - 8793:9793
      - 5555:5555
    volumes:
      - ./backend:/home/backend

  airflow-worker:
    image: backend
    container_name: airflow-worker
    environment:
      - SERVICE=airflow-worker
    env_file:
      - ./backend/.env
      - ./backend/.env.dev
    depends_on:
      - backend
      - db
      - rabbitmq
      - redis
    volumes:
      - ./backend:/home/backend

  worker:
    image: backend
    container_name: worker
    environment:
      - SERVICE=worker
    env_file:
      - ./backend/.env
      - ./backend/.env.dev
    volumes:
      - ./backend:/home/backend
    depends_on:
      - backend
      - redis
      - rabbitmq

  scheduler:
    image: backend
    container_name: scheduler
    environment:
      - SERVICE=scheduler
    env_file:
      - ./backend/.env
      - ./backend/.env.dev
    volumes:
      - ./backend:/home/backend
    depends_on:
      - backend
      - redis
      - rabbitmq

  api:
    image: backend
    container_name: api
    environment:
      - SERVICE=api
    env_file:
      - ./backend/.env
      - ./backend/.env.dev
      - ./backend/.flaskenv
    depends_on:
      - db
      - backend
      - worker
      - redis
      - rabbitmq
      - airflow

    ports:
      - 5000:5000
    volumes:
      - ./backend:/home/backend

  backend:
    image: backend
    container_name: backend
    build:
      context: "./backend"
      dockerfile: "docker/backend.Dockerfile"
    env_file:
      - ./backend/.env
      - ./backend/.env.dev
      - ./backend/.flaskenv
