version: "3"

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

  backend:
    image: backend
    build:
      context: "."
      dockerfile: "backend.Dockerfile"
    volumes:
      - ./backend:/backend
    ports:
      - 5000:5000
    env_file:
      - .env
      - .flaskenv
    depends_on:
      - db

  frontend:
    image: frontend
    build:
      context: "."
      dockerfile: "frontend.Dockerfile"
    volumes:
      - ./frontend:/home/frontend
      - /home/frontend/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    stdin_open: true
