---
version: '3'

services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
    env_file:
      - ./docker/dev.env

  backend:
    image: backend
    container_name: backend
    build:
      context: '.'
      dockerfile: 'backend.Dockerfile'
    ports:
      - 5000:5000
    env_file:
      - ./docker/dev.env
    depends_on:
      - db

#  frontend:
#    image: frontend
#    container_name: frontend
#    build:
#      context: '.'
#      dockerfile: 'frontend.Dockerfile'
#    depends_on:
#      - backend
#    ports:
#      - 3000:3000
#
#  run-db-migrations:
#    image: migrations
#    build:
#      context: '.'
#      dockerfile: 'backend.Dockerfile'
#    volumes:
#      - $PWD/backend:/home/stock-bets/backend
#      - $PWD/db:/home/stock-bets/db
#    environment:
#      - DB_HOST=${DB_HOST}
#      - DB_PORT=${DB_PORT}
#      - DB_USER=${DB_USER}
#      - DB_NAME=${DB_NAME}
#      - DB_PASSWORD=${DB_PASSWORD}
#    entrypoint: ''
#    working_dir: /home/stock-bets/backend
#    command: 'flask db upgrade'
