version: '3'

services:
  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306:3306
    env_file:
      - .env

  backend:
    image: backend:${TAG}
    container_name: backend
    build:
      context: '.'
      dockerfile: 'backend.Dockerfile'
    volumes:
      - ${PWD}/backend:/home/backend
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db

#  frontend:
#    image: frontend
#    container_name: frontend
#    build:
#      context: '.'
#      dockerfile: 'frontend.Dockerfile'
#    depends_on:
#      - backend
#    ports:
#      - 3000:3000
#
