version: "3.8"

services:
  db:
    image: mysql
    container_name: db
    env_file:
      - backend/.env.dev
    ports:
      - 3306:3306
    command: --init-file /init.sql
    volumes:
      - ./backend/docker/init.sql:/init.sql
      - ./backend/docker/.my.cnf:/root/.my.cnf

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    env_file:
      - ./backend/.env.dev
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  airflow:
    image: backend
    container_name: airflow
    environment:
      - SERVICE=airflow
    env_file:
      - ./backend/.env
      - ./backend/.env.dev
    depends_on:
      - backend
      - db
      - rabbitmq
      - redis
      - worker
    ports:
      - 8080:8080
      - 8793:9793
      - 5555:5555
    volumes:
      - ./backend:/home/backend

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - 4563-4599:4563-4599
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - ./.localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  worker:
    image: backend
    container_name: worker
    environment:
      - SERVICE=worker
    env_file:
      - ./backend/.env
      - ./backend/.env.dev
    volumes:
      - ./backend:/home/backend
    depends_on:
      - backend
      - redis
      - rabbitmq
      - localstack

  scheduler:
    image: backend
    container_name: scheduler
    environment:
      - SERVICE=scheduler
    env_file:
      - ./backend/.env
      - ./backend/.env.dev
    volumes:
      - ./backend:/home/backend
    depends_on:
      - backend
      - redis
      - rabbitmq

  api:
    image: backend
    container_name: api
    environment:
      - SERVICE=api
    env_file:
      - ./backend/.env
      - ./backend/.env.dev
      - ./backend/.flaskenv
    depends_on:
      - db
      - backend
      - worker
      - redis
      - rabbitmq
      - airflow
      - localstack
    ports:
      - 5000:5000
      - 8050:8050
    volumes:
      - ./backend:/home/backend
      - ./backend/docker/.my.cnf:/root/.my.cnf

  backend:
    image: backend
    container_name: backend
    build:
      context: "./backend"
      dockerfile: "docker/backend.Dockerfile"
    env_file:
      - ./backend/.env
      - ./backend/.env.dev
      - ./backend/.flaskenv
