"""add session token to users table

Revision ID: 0be8f13749e3
Revises: 570609938096
Create Date: 2020-04-29 18:19:03.777470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be8f13749e3'
down_revision = '570609938096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_token')
    # ### end Alembic commands ###
