"""add index metadata table

Revision ID: 1d3fc8274ad8
Revises: aca61610d540
Create Date: 2020-10-03 23:02:52.262798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3fc8274ad8'
down_revision = 'aca61610d540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=255), nullable=True),
    sa.Column('start_date', sa.Float(precision=32), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('indexes', 'symbol', existing_type=sa.Text, type_=sa.VARCHAR(length=255),
                    existing_nullable=True)

    op.create_index(op.f('indexes_ibfk_1'), 'index_metadata', ['symbol'], unique=False)
    op.create_foreign_key(None, 'indexes', 'index_metadata', ['symbol'], ['symbol'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'indexes', type_='foreignkey')
    op.alter_column('indexes', 'symbol', existing_type=sa.VARCHAR(length=255), type_=sa.Text,
                    existing_nullable=True)
    op.drop_index(op.f('indexes_ibfk_1'), table_name='index_metadata')
    op.drop_table('index_metadata')
    # ### end Alembic commands ###
