"""add real payment support

Revision ID: 1fe73cd2e8bf
Revises: 44b475b8d6bf
Create Date: 2020-07-15 20:22:00.074257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe73cd2e8bf'
down_revision = '44b475b8d6bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('processor', sa.Enum('paypal', name='processors'), nullable=True),
    sa.Column('uuid', sa.Text(), nullable=True),
    sa.Column('winnter_table_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('start', 'refund', 'sidebet', 'overall', name='paymenttypes'), nullable=True),
    sa.Column('direction', sa.Enum('inflow', 'outflow', name='paymentdirection'), nullable=True),
    sa.Column('timestamp', sa.Float(precision=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winnter_table_id'], ['winners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('stakes', sa.Enum('real', 'fun', name='gamestakes'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'stakes')
    op.drop_table('payments')
    # ### end Alembic commands ###
