"""initial data model

Revision ID: 418f26542b6c
Revises: 
Create Date: 2020-05-10 04:26:36.704686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418f26542b6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('mode', sa.Enum('return_weighted', 'consolation_prize', 'winner_takes_all', name='gamemodes'), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('buy_in', sa.Float(), nullable=True),
    sa.Column('n_rebuys', sa.Integer(), nullable=True),
    sa.Column('benchmark', sa.Enum('return_ratio', 'sharpe_ratio', name='benchmarks'), nullable=True),
    sa.Column('side_bets_perc', sa.Float(), nullable=True),
    sa.Column('side_bets_period', sa.Enum('weekly', 'monthly', name='sidebetperiods'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('profile_pic', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('invitee_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'finished', 'cancelled', name='statustypes'), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('open_until', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.Text(), nullable=True),
    sa.Column('trade_type', sa.Enum('long', 'short', name='tradetypes'), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('purchase_time', sa.DateTime(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('sale_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    op.drop_table('game_status')
    op.drop_table('game_invites')
    op.drop_table('users')
    op.drop_table('games')
    # ### end Alembic commands ###
