"""upgrade winners table

Revision ID: 44b475b8d6bf
Revises: fb2f1cfb3026
Create Date: 2020-07-08 18:21:27.794550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b475b8d6bf'
down_revision = 'fb2f1cfb3026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('winners', sa.Column('benchmark', sa.Enum('return_ratio', 'sharpe_ratio', name='benchmarks'), nullable=True))
    op.add_column('winners', sa.Column('end_time', sa.Float(precision=32), nullable=True))
    op.add_column('winners', sa.Column('start_time', sa.Float(precision=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('winners', 'start_time')
    op.drop_column('winners', 'end_time')
    op.drop_column('winners', 'benchmark')
    # ### end Alembic commands ###
