"""add split id to balances

Revision ID: 461b722dc8fb
Revises: 40e1b2b9cb10
Create Date: 2020-09-04 19:29:51.996895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '461b722dc8fb'
down_revision = '40e1b2b9cb10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_balances', sa.Column('stock_split_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game_balances', 'stock_splits', ['stock_split_id'], ['id'])
    op.alter_column('order_status', 'status',
               existing_type=mysql.ENUM('pending', 'fulfilled', 'cancelled', 'expired', 'split_adjust'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_status', 'status',
               existing_type=mysql.ENUM('pending', 'fulfilled', 'cancelled', 'expired', 'split_adjust'),
               nullable=False)
    op.drop_constraint(None, 'game_balances', type_='foreignkey')
    op.drop_column('game_balances', 'stock_split_id')
    # ### end Alembic commands ###
