"""updates for multiplayer mode and indexes

Revision ID: 514d5dd1760b
Revises: 44b475b8d6bf
Create Date: 2020-07-18 00:54:00.055398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '514d5dd1760b'
down_revision = '44b475b8d6bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(precision=32), nullable=True),
    sa.Column('timestamp', sa.Float(precision=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('game_mode', sa.Enum('single_player', 'multi_player', 'public', name='gamemodes'), nullable=True))
    op.drop_column('games', 'n_rebuys')
    op.drop_column('games', 'mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('mode', mysql.ENUM('return_weighted', 'consolation_prize', 'winner_takes_all'), nullable=True))
    op.add_column('games', sa.Column('n_rebuys', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('games', 'game_mode')
    op.drop_table('indexes')
    # ### end Alembic commands ###
