"""add stock splits and update balances

Revision ID: 53531a199d1a
Revises: bf27fc886b9a
Create Date: 2020-08-20 16:58:00.411368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53531a199d1a'
down_revision = 'bf27fc886b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('numerator', sa.Integer(), nullable=True),
    sa.Column('denominator', sa.Integer(), nullable=True),
    sa.Column('exec_date', sa.Float(precision=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('game_balances', sa.Column('transaction_type', sa.Enum('stock_purchase', 'stock_sale', 'stock_dividend', 'stock_split', name='gamebalancetransactiontypes'), nullable=True))
    op.alter_column('game_status', 'status',
               existing_type=mysql.ENUM('pending', 'active', 'finished', 'expired', 'cancelled'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_status', 'status',
               existing_type=mysql.ENUM('pending', 'active', 'finished', 'expired', 'cancelled'),
               nullable=False)
    op.drop_column('game_balances', 'transaction_type')
    op.drop_table('stock_splits')
    # ### end Alembic commands ###
