"""update user table

Revision ID: 5361bcc1de12
Revises: 720766fdbaf3
Create Date: 2020-05-13 02:47:09.392055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5361bcc1de12'
down_revision = '720766fdbaf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider', sa.Enum('google', 'facebook', 'twitter', name='oauthproviders'), nullable=True))
    op.add_column('users', sa.Column('resource_uuid', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resource_uuid')
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
