"""game mode for single and multiplayer

Revision ID: 60d9c4e4852f
Revises: 44b475b8d6bf
Create Date: 2020-07-16 00:08:09.186318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60d9c4e4852f'
down_revision = '44b475b8d6bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(precision=32), nullable=True),
    sa.Column('timestamp', sa.Float(precision=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('game_mode', sa.Enum('single_player', 'multi_player', name='gamemodes'), nullable=True))
    op.drop_column('games', 'mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('mode', mysql.ENUM('return_weighted', 'consolation_prize', 'winner_takes_all'), nullable=True))
    op.drop_column('games', 'game_mode')
    op.drop_table('indexes')
    # ### end Alembic commands ###
