"""add stock dividends

Revision ID: 64208ffde6f0
Revises: 461b722dc8fb
Create Date: 2020-09-27 20:56:02.466558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64208ffde6f0'
down_revision = '461b722dc8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(precision=32), nullable=True),
    sa.Column('exec_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('game_balances', sa.Column('dividend_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game_balances', 'dividends', ['dividend_id'], ['id'])
    op.alter_column('games', 'duration',
               existing_type=mysql.DOUBLE(asdecimal=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'duration',
               existing_type=mysql.DOUBLE(asdecimal=True),
               nullable=False)
    op.drop_constraint(None, 'game_balances', type_='foreignkey')
    op.drop_column('game_balances', 'dividend_id')
    op.drop_table('dividends')
    # ### end Alembic commands ###
