"""add winners table

Revision ID: 656925ba7545
Revises: d58e9f252421
Create Date: 2020-06-16 04:53:32.103346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656925ba7545'
down_revision = 'd58e9f252421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(precision=32), nullable=True),
    sa.Column('timestamp', sa.Float(precision=32), nullable=True),
    sa.Column('payout', sa.Float(precision=32), nullable=True),
    sa.Column('type', sa.Enum('sidebet', 'overall', name='payouttype'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winners')
    # ### end Alembic commands ###
