"""add transactions and balances

Revision ID: 720766fdbaf3
Revises: 9bc14369ab38
Create Date: 2020-05-13 02:09:39.682577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '720766fdbaf3'
down_revision = '9bc14369ab38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.Text(), nullable=True),
    sa.Column('buy_or_sell', sa.Enum('limit', 'market', 'stop', name='ordertype'), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('order_type', sa.Enum('limit', 'market', 'stop', name='ordertype'), nullable=True),
    sa.Column('time_in_force', sa.Enum('day', 'until_cancelled', name='timeinforce'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('order_status', sa.Enum('pending', 'fulfilled', 'cancelled', 'expired', name='orderstatustypes'), nullable=True),
    sa.Column('clear_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('balance_type', sa.Enum('actual_cash', 'virtual_cash', 'virtual_stock', name='balancetypes'), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('positions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('game_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ticker', mysql.TEXT(), nullable=True),
    sa.Column('trade_type', mysql.ENUM('long', 'short'), nullable=True),
    sa.Column('shares', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchase_price', mysql.FLOAT(), nullable=True),
    sa.Column('purchase_time', mysql.DATETIME(), nullable=True),
    sa.Column('sale_price', mysql.FLOAT(), nullable=True),
    sa.Column('sale_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='positions_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='positions_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('balances')
    op.drop_table('transactions')
    op.drop_table('orders')
    # ### end Alembic commands ###
