"""add column indexes

Revision ID: 744c743636c4
Revises: b50d0c505d3e
Create Date: 2020-08-04 00:02:04.316994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744c743636c4'
down_revision = 'b50d0c505d3e'
branch_labels = None
depends_on = None


def upgrade():
    # make some alterations to text columns so that they are VARCHARs with specified character type
    op.alter_column('balances_and_prices_cache', 'symbol', existing_type=sa.Text, type_=sa.VARCHAR(length=255),
                    existing_nullable=True)
    op.alter_column('external_invites', 'invited_email', existing_type=sa.Text, type_=sa.VARCHAR(length=255),
                    existing_nullable=True)
    op.alter_column('game_balances', 'symbol', existing_type=sa.Text, type_=sa.VARCHAR(length=255),
                    existing_nullable=True)
    op.alter_column('indexes', 'symbol', existing_type=sa.Text, type_=sa.VARCHAR(length=255),
                    existing_nullable=True)
    op.alter_column('orders', 'symbol', existing_type=sa.Text, type_=sa.VARCHAR(length=255),
                    existing_nullable=True)
    op.alter_column('symbols', 'symbol', existing_type=sa.Text, type_=sa.VARCHAR(length=255),
                    existing_nullable=True)
    op.alter_column('symbols', 'name', existing_type=sa.Text, type_=sa.VARCHAR(length=255),
                    existing_nullable=True)
    op.alter_column('prices', 'symbol', existing_type=sa.Text, type_=sa.VARCHAR(length=255),
                    existing_nullable=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_balances_and_prices_cache_symbol'), 'balances_and_prices_cache', ['symbol'], unique=False)
    op.create_index(op.f('ix_balances_and_prices_cache_timestamp'), 'balances_and_prices_cache', ['timestamp'], unique=False)
    op.create_index(op.f('ix_external_invites_invited_email'), 'external_invites', ['invited_email'], unique=False)
    op.create_index(op.f('ix_external_invites_status'), 'external_invites', ['status'], unique=False)
    op.create_index(op.f('ix_external_invites_timestamp'), 'external_invites', ['timestamp'], unique=False)
    op.create_index(op.f('ix_external_invites_type'), 'external_invites', ['type'], unique=False)
    op.create_index(op.f('ix_friends_status'), 'friends', ['status'], unique=False)
    op.create_index(op.f('ix_friends_timestamp'), 'friends', ['timestamp'], unique=False)
    op.create_index(op.f('ix_game_balances_balance'), 'game_balances', ['balance'], unique=False)
    op.create_index(op.f('ix_game_balances_balance_type'), 'game_balances', ['balance_type'], unique=False)
    op.create_index(op.f('ix_game_balances_symbol'), 'game_balances', ['symbol'], unique=False)
    op.create_index(op.f('ix_game_balances_timestamp'), 'game_balances', ['timestamp'], unique=False)
    op.create_index(op.f('ix_game_invites_status'), 'game_invites', ['status'], unique=False)
    op.create_index(op.f('ix_game_invites_timestamp'), 'game_invites', ['timestamp'], unique=False)
    op.create_index(op.f('ix_game_status_status'), 'game_status', ['status'], unique=False)
    op.create_index(op.f('ix_indexes_symbol'), 'indexes', ['symbol'], unique=False)
    op.create_index(op.f('ix_indexes_timestamp'), 'indexes', ['timestamp'], unique=False)
    op.create_index(op.f('ix_indexes_value'), 'indexes', ['value'], unique=False)
    op.create_index(op.f('ix_order_status_status'), 'order_status', ['status'], unique=False)
    op.create_index(op.f('ix_order_status_timestamp'), 'order_status', ['timestamp'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_prices_price'), 'prices', ['price'], unique=False)
    op.create_index(op.f('ix_prices_symbol'), 'prices', ['symbol'], unique=False)
    op.create_index(op.f('ix_prices_timestamp'), 'prices', ['timestamp'], unique=False)
    op.create_index(op.f('ix_symbols_name'), 'symbols', ['name'], unique=False)
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # make some alterations to text columns so that they are VARCHARs with specified character type
    op.alter_column('balances_and_prices_cache', 'symbol', existing_type=sa.VARCHAR(length=255), type_=sa.Text,
                    existing_nullable=True)
    op.alter_column('external_invites', 'invited_email', existing_type=sa.VARCHAR(length=255), type_=sa.Text,
                    existing_nullable=True)
    op.alter_column('game_balances', 'symbol', existing_type=sa.VARCHAR(length=255), type_=sa.Text,
                    existing_nullable=True)
    op.alter_column('indexes', 'symbol', existing_type=sa.VARCHAR(length=255), type_=sa.Text,
                    existing_nullable=True)
    op.alter_column('orders', 'symbol', existing_type=sa.VARCHAR(length=255), type_=sa.Text,
                    existing_nullable=True)
    op.alter_column('symbols', 'symbol', existing_type=sa.VARCHAR(length=255), type_=sa.Text,
                    existing_nullable=True)
    op.alter_column('symbols', 'name', existing_type=sa.VARCHAR(length=255), type_=sa.Text,
                    existing_nullable=True)
    op.alter_column('prices', 'symbol', existing_type=sa.VARCHAR(length=255), type_=sa.Text,
                    existing_nullable=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_name'), table_name='symbols')
    op.drop_index(op.f('ix_prices_timestamp'), table_name='prices')
    op.drop_index(op.f('ix_prices_symbol'), table_name='prices')
    op.drop_index(op.f('ix_prices_price'), table_name='prices')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_order_status_timestamp'), table_name='order_status')
    op.drop_index(op.f('ix_order_status_status'), table_name='order_status')
    op.drop_index(op.f('ix_indexes_value'), table_name='indexes')
    op.drop_index(op.f('ix_indexes_timestamp'), table_name='indexes')
    op.drop_index(op.f('ix_indexes_symbol'), table_name='indexes')
    op.drop_index(op.f('ix_game_status_status'), table_name='game_status')
    op.drop_index(op.f('ix_game_invites_timestamp'), table_name='game_invites')
    op.drop_index(op.f('ix_game_invites_status'), table_name='game_invites')
    op.drop_index(op.f('ix_game_balances_timestamp'), table_name='game_balances')
    op.drop_index(op.f('ix_game_balances_symbol'), table_name='game_balances')
    op.drop_index(op.f('ix_game_balances_balance_type'), table_name='game_balances')
    op.drop_index(op.f('ix_game_balances_balance'), table_name='game_balances')
    op.drop_index(op.f('ix_friends_timestamp'), table_name='friends')
    op.drop_index(op.f('ix_friends_status'), table_name='friends')
    op.drop_index(op.f('ix_external_invites_type'), table_name='external_invites')
    op.drop_index(op.f('ix_external_invites_timestamp'), table_name='external_invites')
    op.drop_index(op.f('ix_external_invites_status'), table_name='external_invites')
    op.drop_index(op.f('ix_external_invites_invited_email'), table_name='external_invites')
    op.drop_index(op.f('ix_balances_and_prices_cache_timestamp'), table_name='balances_and_prices_cache')
    op.drop_index(op.f('ix_balances_and_prices_cache_symbol'), table_name='balances_and_prices_cache')
    # ### end Alembic commands ###
