"""empty message

Revision ID: 7c611bf6e432
Revises: 514d5dd1760b
Create Date: 2020-07-19 22:50:17.174610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c611bf6e432'
down_revision = '514d5dd1760b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('invited_email', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('invited', 'accepted', 'error', name='externalinvitestatus'), nullable=True),
    sa.Column('timestamp', sa.Float(precision=32), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_invites')
    # ### end Alembic commands ###
