"""add real payments table

Revision ID: 848a9d3e8e2c
Revises: 6a1fd042d869
Create Date: 2020-08-09 04:32:40.990508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '848a9d3e8e2c'
down_revision = '6a1fd042d869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('processor', sa.Enum('paypal', name='processors'), nullable=True),
    sa.Column('uuid', sa.Text(), nullable=True),
    sa.Column('winner_table_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('start', 'refund', 'sidebet', 'overall', name='paymenttypes'), nullable=True),
    sa.Column('direction', sa.Enum('inflow', 'outflow', name='paymentdirection'), nullable=True),
    sa.Column('timestamp', sa.Float(precision=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_table_id'], ['winners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'provider',
               existing_type=mysql.ENUM('google', 'facebook', 'twitter', 'stockbets'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'provider',
               existing_type=mysql.ENUM('google', 'facebook', 'twitter', 'stockbets'),
               nullable=False)
    op.drop_table('payments')
    # ### end Alembic commands ###
