"""update time info for pending games

Revision ID: 85ea0b722c79
Revises: 418f26542b6c
Create Date: 2020-05-10 07:13:00.003327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85ea0b722c79'
down_revision = '418f26542b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_invites', sa.Column('open_until', sa.DateTime(), nullable=True))
    op.add_column('game_invites', sa.Column('opened_at', sa.DateTime(), nullable=True))
    op.add_column('game_status', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('game_status', 'opened_at')
    op.drop_column('game_status', 'started_at')
    op.drop_column('game_status', 'ends_at')
    op.drop_column('game_status', 'open_until')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_status', sa.Column('open_until', mysql.DATETIME(), nullable=True))
    op.add_column('game_status', sa.Column('ends_at', mysql.DATETIME(), nullable=True))
    op.add_column('game_status', sa.Column('started_at', mysql.DATETIME(), nullable=True))
    op.add_column('game_status', sa.Column('opened_at', mysql.DATETIME(), nullable=True))
    op.drop_column('game_status', 'updated_at')
    op.drop_column('game_invites', 'opened_at')
    op.drop_column('game_invites', 'open_until')
    # ### end Alembic commands ###
