"""update games tables and remove invites

Revision ID: 9bc14369ab38
Revises: 418f26542b6c
Create Date: 2020-05-11 18:02:58.211184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bc14369ab38'
down_revision = '418f26542b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_invites')
    op.add_column('game_status', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('game_status', sa.Column('users', sa.JSON(), nullable=True))
    op.drop_column('game_status', 'ends_at')
    op.drop_column('game_status', 'opened_at')
    op.drop_column('game_status', 'open_until')
    op.drop_column('game_status', 'started_at')
    op.add_column('games', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('invite_window', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'games', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'invite_window')
    op.drop_column('games', 'creator_id')
    op.add_column('game_status', sa.Column('started_at', mysql.DATETIME(), nullable=True))
    op.add_column('game_status', sa.Column('open_until', mysql.DATETIME(), nullable=True))
    op.add_column('game_status', sa.Column('opened_at', mysql.DATETIME(), nullable=True))
    op.add_column('game_status', sa.Column('ends_at', mysql.DATETIME(), nullable=True))
    op.drop_column('game_status', 'users')
    op.drop_column('game_status', 'timestamp')
    op.create_table('game_invites',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creator_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invitee_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('game_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='game_invites_ibfk_1'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='game_invites_ibfk_2'),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], name='game_invites_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
