"""add indexes to balances cache and prices

Revision ID: ad651650f60c
Revises: 4b2b5e6d761d
Create Date: 2020-08-04 19:29:05.390467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad651650f60c'
down_revision = '4b2b5e6d761d'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column('balances_and_prices_cache', 'symbol', existing_type=sa.Text, type_=sa.VARCHAR(length=255),
                    existing_nullable=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('balances_and_prices_game_user_timestamp_ix', 'balances_and_prices_cache', ['game_id', 'user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_balances_and_prices_cache_symbol'), 'balances_and_prices_cache', ['symbol'], unique=False)
    op.create_index(op.f('ix_balances_and_prices_cache_timestamp'), 'balances_and_prices_cache', ['timestamp'], unique=False)
    op.create_index('prices_symbol_timestamp_ix', 'prices', ['symbol', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    op.alter_column('balances_and_prices_cache', 'symbol', existing_type=sa.VARCHAR(length=255), type_=sa.Text,
                    existing_nullable=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('prices_symbol_timestamp_ix', table_name='prices')
    op.drop_index(op.f('ix_balances_and_prices_cache_timestamp'), table_name='balances_and_prices_cache')
    op.drop_index(op.f('ix_balances_and_prices_cache_symbol'), table_name='balances_and_prices_cache')
    op.drop_index('balances_and_prices_game_user_timestamp_ix', table_name='balances_and_prices_cache')
    # ### end Alembic commands ###
