"""empty message

Revision ID: ade3426005ad
Revises: 44b475b8d6bf
Create Date: 2020-07-19 02:12:50.262931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade3426005ad'
down_revision = '44b475b8d6bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('invited_email', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('invited', 'accepted', 'error', name='externalinvitestatus'), nullable=True),
    sa.Column('timestamp', sa.Float(precision=32), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_invites')
    # ### end Alembic commands ###
