"""initial data model

Revision ID: b376ebc02bcb
Revises: 
Create Date: 2020-05-15 15:43:41.119302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b376ebc02bcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('profile_pic', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('provider', sa.Enum('google', 'facebook', 'twitter', name='oauthproviders'), nullable=True),
    sa.Column('resource_uuid', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('mode', sa.Enum('return_weighted', 'consolation_prize', 'winner_takes_all', name='gamemodes'), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('buy_in', sa.Float(), nullable=True),
    sa.Column('n_rebuys', sa.Integer(), nullable=True),
    sa.Column('benchmark', sa.Enum('return_ratio', 'sharpe_ratio', name='benchmarks'), nullable=True),
    sa.Column('side_bets_perc', sa.Float(), nullable=True),
    sa.Column('side_bets_period', sa.Enum('weekly', 'monthly', name='sidebetperiods'), nullable=True),
    sa.Column('invite_window', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'finished', 'cancelled', name='gamestatustypes'), nullable=True),
    sa.Column('users', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.Text(), nullable=True),
    sa.Column('buy_or_sell', sa.Enum('buy', 'sell', name='buyorsell'), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('order_type', sa.Enum('market', 'limit', 'stop', name='ordertypes'), nullable=True),
    sa.Column('time_in_force', sa.Enum('day', 'until_cancelled', name='timeinforce'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'fulfilled', 'cancelled', 'expired', name='orderstatustypes'), nullable=True),
    sa.Column('clear_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('balance_type', sa.Enum('actual_cash', 'virtual_cash', 'virtual_stock', name='balancetypes'), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balances')
    op.drop_table('transactions')
    op.drop_table('orders')
    op.drop_table('game_status')
    op.drop_table('games')
    op.drop_table('users')
    op.drop_table('symbols')
    # ### end Alembic commands ###
