"""add balances and prices cache

Revision ID: b50d0c505d3e
Revises: bb1e1a2197c1
Create Date: 2020-08-01 16:19:47.516586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b50d0c505d3e'
down_revision = 'bb1e1a2197c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances_and_prices_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Float(precision=32), nullable=True),
    sa.Column('balance', sa.Float(precision=32), nullable=True),
    sa.Column('price', sa.Float(precision=32), nullable=True),
    sa.Column('value', sa.Float(precision=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('external_invites', 'status',
               existing_type=mysql.ENUM('invited', 'accepted', 'error', 'declined'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_invites', 'status',
               existing_type=mysql.ENUM('invited', 'accepted', 'error', 'declined'),
               nullable=False)
    op.drop_table('balances_and_prices_cache')
    # ### end Alembic commands ###
