"""update games table

Revision ID: c8740746f9ee
Revises: 7f973d2726ef
Create Date: 2020-05-07 16:32:00.655635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8740746f9ee'
down_revision = '7f973d2726ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_status', sa.Column('ends_at', sa.DateTime(), nullable=True))
    op.add_column('game_status', sa.Column('open_until', sa.DateTime(), nullable=True))
    op.add_column('game_status', sa.Column('opened_at', sa.DateTime(), nullable=True))
    op.add_column('game_status', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.drop_column('game_status', 'timestamp')
    op.add_column('games', sa.Column('buy_in', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('n_rebuys', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('side_bets_perc', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('side_bets_period', sa.Enum('WEEKLY', 'MONTHLY', name='sidebetperiods'), nullable=True))
    op.drop_column('games', 'opened_at')
    op.drop_column('games', 'min_buy')
    op.drop_column('games', 'max_buy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('max_buy', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    op.add_column('games', sa.Column('min_buy', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    op.add_column('games', sa.Column('opened_at', mysql.DATETIME(), nullable=True))
    op.drop_column('games', 'side_bets_period')
    op.drop_column('games', 'side_bets_perc')
    op.drop_column('games', 'n_rebuys')
    op.drop_column('games', 'buy_in')
    op.add_column('game_status', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.drop_column('game_status', 'started_at')
    op.drop_column('game_status', 'opened_at')
    op.drop_column('game_status', 'open_until')
    op.drop_column('game_status', 'ends_at')
    # ### end Alembic commands ###
